create database customer_behavior;
use customer_behavior;
select * from customer_table;

-- Q1. What is the total revenue generated by male vs. female customers?
select sum(purchase_amount) as revenue,gender from customer_table
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer_table
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer_table);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, Round(avg(review_rating),2) as Average_product_rating from customer_table
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(avg(purchase_amount),2) as average_purchase_amount from customer_table
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select count(customer_id),subscription_status,round(avg(purchase_amount),2) as average_spend,sum(purchase_amount) as total_revenue from customer_table
group by subscription_status;

-- Improtant question -------
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
 ROUND(
        100.0 * SUM(CASE 
                        WHEN discount_applied ='Yes'THEN 1 
                        ELSE 0 
                    END) 
        / COUNT(*),
        2
    ) AS discount_percentage
from customer_table
group by item_purchased
order by discount_percentage desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as ( 
select customer_id,previous_purchases, 
CASE 
   when previous_purchases=1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   End as customer_segment
   from customer_table
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
select  count(customer_id) as number_of_purchases,item_purchased,category from customer_table
group by item_purchased,category
order by number_of_purchases desc limit 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyer from customer_table
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 

select sum(purchase_amount) as revenue, age_group from customer_table
group by age_group
order by revenue desc ;